export { default as NavBar } from "./NavBar/NavBar";
export { default as Banner } from "./Banner/Banner";
export { default as PageStatistics } from "./PageStatistics/PageStatistics";
export { default as Card } from "./Card/Card";
export { default as About } from "./About/About";
export { default as Feature } from "./Feature/Feature";
export { default as Applink } from "./Applink/Applink";
export { default as Pricing } from "./Pricing/Pricing";
export { default as StatisticsCard } from "./Utilities/StatisticsCard";
